Ensure tomcat native installs and starts correctly
ansible-middleware/jws-ansible-playbook pull request #120
Opened 2022-05-18 09:17 UTC by guidograzioli

Fix #115 
Fix #114

2022-05-18 11:15 UTC, guidograzioli commented
Apache tomcat does not distribute native archives, so we can only test this on JWS

2022-05-18 12:44 UTC, csutherl requested changes
The error check should be modified a bit, but otherwise looks good.

2022-05-18 12:44 UTC, csutherl commented on roles/jws_validation/tasks/catalina_out.yml
> +      - "{{ 'ERROR' not in catalina_out.content }}"
This check should be for SEVERE and/or WARNING rather than ERROR since ERROR isn't always present in the exception output.

2022-05-18 12:45 UTC, csutherl commented
> Apache tomcat does not distribute native archives, so we can only test this on JWS

I was thinking about adding a feature to download the sources for tomcat-native from the ASF to build and test it with the Apache Tomcat distribution as well. Then we could test it outside of JWS as well, if we wanted.

2022-05-18 13:27 UTC, csutherl commented on roles/jws_validation/tasks/catalina_out.yml
> +      - "{{ 'ERROR' not in catalina_out.content }}"
That will work. I figured adding a WARNING because there shouldn't be any warnings either, but just checking for SEVERE and verifying that other features (like tomcat-native) are enabled correctly works.

2022-05-18 15:08 UTC, csutherl requested changes
Just one minor doc change request, but everything else looks OK.

2022-05-18 15:08 UTC, csutherl commented on roles/jws/README.md
> +|`tomcat_native`| Install native bits (JWS)| `False` |
Since you can use tomcat-native with or without JWS now we should remove the '(JWS)' bit.

2022-05-18 19:15 UTC, csutherl approved these changes

2022-05-18 19:19 UTC, csutherl requested changes
The molecule test is failing because of an undefined variable, `tomcat_zipfile`.

2022-05-18 19:19 UTC, csutherl commented on molecule/local_with_native/prepare.yml
> +        url:  "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.50/bin/{{ tomcat_zipfile }}"
I don't think you can rely on defaults from the collection in the prepare step, so you'll have to define this in `vars` for this playbook to use it.

2022-05-19 15:59 UTC, guidograzioli commented on molecule/local_with_native/prepare.yml
> +        url:  "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.50/bin/{{ tomcat_zipfile }}"
This was not easy; jws has catalina.home/lib in ld_library_path while tomcat does not... added to tomcat.conf loaded by systemd unit

2022-05-23 19:28 UTC, csutherl approved these changes
LGTM

2022-05-23 19:28 UTC, csutherl commented on molecule/local_with_native/prepare.yml
> +        url:  "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.50/bin/{{ tomcat_zipfile }}"
Yeah, I think that will work fine. The JWS install sets the LD_LIBRARY_PATH in setenv.sh.

2022-05-24 15:43 UTC, merged