Rename vars
ansible-middleware/jws-ansible-playbook pull request #154
Opened 2022-08-10 13:23 UTC by rpelisse

2022-08-10 14:15 UTC, csutherl requested changes
I don't see any changes to `roles/jws/vars/main.yml`? Shouldn't we be updating the variables in there too?

2022-08-10 14:15 UTC, csutherl commented on roles/jws/defaults/main.yml
> +jws_version: 9.0.60
This isn't a valid JWS version. I think we talked about there being an issue with updating default values automatically, but if we're going to call it jws_version it should have a valid JWS version :)

2022-08-10 14:15 UTC, csutherl commented on roles/jws/defaults/main.yml
>  tomcat_catalina_base: "{{ lookup('env','CATALINA_BASE') }}"
Since we've already changed everything else, why not change this block too?

2022-08-10 14:24 UTC, rpelisse commented
Yep, the default value for jws_version will disappear upstream( jws_version will be undefined upstream). 
Noted for the 39 to 49

2022-08-10 19:22 UTC, csutherl commented on roles/jws/vars/main.yml
>  tomcat:
Do you not need a change here to from tomcat to jws?

2022-08-10 19:24 UTC, csutherl approved these changes
That's a big PR, but I think it LGTM :smile: Just had one commented about the `roles/jws/vars/main.yml` but it doesn't keep me from giving a +1.

2022-08-11 08:58 UTC, rpelisse commented on roles/jws/vars/main.yml
>  tomcat:
Yes, we do! And that's the next step :) (this PR being already quite huge)

2022-08-11 09:39 UTC, merged