Updating redhat_csp_download to use certified collection
ansible-middleware/jws-ansible-playbook pull request #28
Opened 2021-11-23 15:31 UTC by hcherukuri

Updating token in ansible.cfg

2021-11-23 15:34 UTC, hcherukuri commented
Secrets are not available for the PR, so the CI will fail.  Please see on my fork branch: https://github.com/hcherukuri/jws-ansible-playbook/actions/runs/1495461824

2021-11-23 15:53 UTC, gzaronikas approved these changes
Looks good to me. Locally with a token, CI molecule test passes so I'm good with that. 
As a note to ourselves we should find a way to split the tests though in the future to avoid any GH CI breaks.

2021-11-25 13:58 UTC, rpelisse commented on .github/workflows/ci.yml
> +    steps:
@hcherukuri for the purpose of having clean commit, can you remove those extra whitespaces?

2021-11-25 13:58 UTC, rpelisse commented on .gitignore
> +*.tar.gz
I would keep *.zip on top of *.tar.gz

2021-11-25 13:59 UTC, rpelisse requested changes
@hcherukuri just a few minor tweaks, otherwise LGTM!

2021-11-25 13:59 UTC, hcherukuri commented on .gitignore
> +*.tar.gz
Ok I will add .

2021-11-25 14:03 UTC, rpelisse approved these changes

2021-11-25 15:04 UTC, merged