The JWS installation option should allow you to exclude natives
ansible-middleware/jws-ansible-playbook pull request #97
Opened 2022-04-22 15:45 UTC by rpelisse

Fixed #73 (and reduce code duplication)

2022-04-22 16:38 UTC, rpelisse commented
@guidograzioli Can you review and approve? 
 @csutherl can you test to be sure that native is no longer an obligation?

2022-04-22 16:49 UTC, guidograzioli commented
I think this PR contains many same commits as #89? Can you check?

2022-04-25 07:04 UTC, rpelisse commented
@guidograzioli yes, it's designed to be merge after PR89.

2022-04-25 08:01 UTC, guidograzioli commented
LGTM!

2022-04-25 08:01 UTC, guidograzioli approved these changes

2022-04-25 18:53 UTC, csutherl commented
I cloned the PR branch and tested it a bit, and found that there's one place you didn't add a `tomcat_native` check which was causing the native zipfile to still be required. Adding a check for `tomcat_native == True` to the `when` block in [roles/jws/tasks/install/zipfiles.yml#L16](https://github.com/ansible-middleware/jws-ansible-playbook/blob/main/roles/jws/tasks/install/zipfiles.yml#L16) makes it work as expected.

I did notice another thing that we may want to address. If you run the script with the default `tomcat_native: False` and then run it again after setting `tomcat_native: True` it unpacks the zip as expected, but doesn't notify a restart of the Tomcat service. I had to manually restart the process for tomcat_native to be picked up. If we think this behavior is ok, we should probably document that a restart is required (after someone checks to make sure it's not an env problem).

2022-04-25 18:53 UTC, csutherl commented on roles/jws/tasks/install/fetch_zipfile_from_rhn_and_deploy.yml
> +- name: "Check downloaded archive local_path.stat.path }}/{{ zipfile }}"
You're missing the opening curly braces for the variable here.

2022-04-26 11:29 UTC, rpelisse commented
@csutherl you are a god send! Thank you for spotting all of that. I think I've fixed everything and this PR should be good to go. However, if you can review (and /or test it) one last time, that certainly can't hurt :)

2022-04-26 11:36 UTC, csutherl commented
@rpelisse I have a particular set of skills (spotting typos) :laughing: My day is kind of full today, but I should be able to give it one more go this afternoon and provide some feedback. Thanks for being so quick to respond!

2022-04-26 19:04 UTC, csutherl requested changes
I just tested the latest commit and it still doesn't work unless you add the `tomcat_native` check to `roles/jws/tasks/install/zipfiles.yml` so that the `zipfiles` list doesn't require the libtcnative.so. Without that check in place, you see the following failure when you run the playbook (having `jws_version` and `tomcat_install_method` defined):

```
TASK [middleware_automation.jws.jws : Install Jboss Web Server and required binaries from local zipfiles (install method: rhn_zipfiles] **************************************************************************************************************************************************************************************
changed: [localhost] => (item={'src': 'jws-5.6.0-application-server.zip', 'creates': '/opt/jws-5.6/tomcat/bin'})
failed: [localhost] (item={'src': 'jws-5.6.0-application-server-RHEL35-x86_64.zip', 'creates': '/opt/jws-5.6/tomcat/lib/libtcnative-1.so'}) => {"ansible_loop_var": "item", "changed": false, "item": {"creates": "/opt/jws-5.6/tomcat/lib/libtcnative-1.so", "src": "jws-5.6.0-application-server-RHEL35-x86_64.zip"}, "msg": "Source '/opt/jws-5.6.0-application-server-RHEL35-x86_64.zip' does not exist"}
```

2022-04-26 19:04 UTC, csutherl commented on roles/jws/tasks/install/fetch_zipfile_from_rhn_and_deploy.yml
> +- name: "Check downloaded archive local_path.stat.path }}/{{ zipfile }}"
The opening braces are still missing :(

2022-04-27 08:14 UTC, rpelisse commented on roles/jws/tasks/install/fetch_zipfile_from_rhn_and_deploy.yml
> +- name: "Check downloaded archive local_path.stat.path }}/{{ zipfile }}"
Darn! This was the very first thing I fixed up! It must have been squashed when I rebase :(

2022-04-27 08:46 UTC, rpelisse commented
@csutherl OK, confirmed... Rebasing has removed all my changes... I guess "Don't rebase without testing". I'm going to update the PR. Sorry for that :(

2022-04-27 13:37 UTC, rpelisse commented
@csutherl OK, added back the change, tested locally. But if you have the time to review again, that'll be awesome.

2022-04-27 14:43 UTC, csutherl approved these changes
LGTM! I appreciate you adding the restart notification, that works well too.

2022-04-27 14:48 UTC, rpelisse commented
@csutherl Cool! No problem, it was a good idea to add notify :) Then I'll merge this right away :)

2022-04-27 14:48 UTC, merged