A first pass at creating a molecule test which requires JWS
ansible-middleware/jws-ansible-playbook pull request #99
Opened 2022-04-27 14:22 UTC by csutherl

2022-04-28 01:02 UTC, csutherl commented
@rpelisse OK, this latest commit (22f9129) works using some sample files (keystore, properties, data file) so it's ready for review. This iteration requires users to provide a vault that's already configured along with the properties file and data file (which we should probably make optional since it's not required). I was also thinking about adding a new switch like `tomcat.vault.init` which will execute the call to `keytool` and the vault init that was there before. After the init, users would have to encrypt their data and copy the appropriate strings into the config files. Thoughts?

2022-04-28 07:47 UTC, guidograzioli requested changes

2022-04-28 07:47 UTC, guidograzioli commented on roles/jws/tasks/main.yml
> +            mode: 0750
this (and below) should be 0640 or maybe 0440

2022-04-28 07:47 UTC, guidograzioli commented on roles/jws/templates/catalina.properties.j2
> +# Licensed to the Apache Software Foundation (ASF) under one or more
Please add on first line:

    # {{ ansible_managed }}

2022-04-28 07:47 UTC, guidograzioli commented on roles/jws_validation/tasks/main.yml
> +    - tomcat_vault_enable == True
no need for ``== True`` here, just ```when: tomcat_vault_enabled```

2022-05-03 14:58 UTC, csutherl commented
This test has to live elsewhere :/

2022-05-03 14:58 UTC, closed without merging